// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.imc.mattermost-plugin-pingboard",
  "name": "Pingboard",
  "description": "Adds information from Pingboard to user popover.",
  "homepage_url": "https://github.com/imc-trading/mattermost-plugin-pingboard",
  "support_url": "https://github.com/imc-trading/mattermost-plugin-pingboard/issues",
  "release_notes_url": "https://github.com/imc-trading/mattermost-plugin-pingboard/releases/tag/v1.0.0",
  "version": "1.0.0",
  "min_server_version": "5.39.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "If you don't want to set the client secret here, you can leave it empty and instead set environment var 'MM_PLUGIN_PINGBOARD_CLIENT_SECRET'.",
    "settings": [
      {
        "key": "pingboardApiClientID",
        "display_name": "Pingboard API client ID",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": null
      },
      {
        "key": "pingboardApiClientSecret",
        "display_name": "Pingboard API client secret",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": null
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
